---
AWSTemplateFormatVersion: '2010-09-09'
Description: Glue job, triggers and crawlers
Parameters:
  GlueJobRoleArn:
    Description: Glue job role
    Type: String
Resources:
  GlueJobExample:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: "s3://aws-glue-scripts//prod-job1"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: cf-job1
      Role: !Ref GlueJobRoleArn