---
AWSTemplateFormatVersion: '2010-09-09'
Description: Glue job, triggers and crawlers
Parameters:
  GlueJobRoleArn:
    Description: Glue job role
    Type: String
  GlueMainBucketName:
    Description: Glue main bucket name
    Type: String
Resources:
  GlueJobExample:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${GlueMainBucketName}/com/glue/jobs/JobExample.scala"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        "--BusinessSourcePath": !Sub "s3://${GlueMainBucketName}/resources/"
        "--extra-jars": !Sub "s3://${GlueMainBucketName}/lib/GlueEtlExample.jar"
        "--job-language": "scala"
        "--class": "com.glue.jobs.JobExample"
        "--enable-metrics": "true"
        "--job-bookmark-option": "job-bookmark-disable"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: job-example
      Role: !Ref GlueJobRoleArn