---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for glue job etl example
#Parameters:
#  InfraBucket:
#    Description: Infrastructure bucket name
#    Type: String
Resources:
  GlueStack:
    DependsOn: S3Stack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        GlueJobRoleArn:
          !GetAtt IamStack.Outputs.GlueJobRoleArn
        GlueMainBucketName:
          !GetAtt S3Stack.Outputs.GlueMainBucketName
      TemplateURL: 'glue-stack.yml'
      TimeoutInMinutes: '5'
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'iam-stack.yml'
      TimeoutInMinutes: '5'
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 's3-stack.yml'
      TimeoutInMinutes: '5'